### ISSUE TITLE
How to run docker-snapcrawl on Windows

### ISSUE THREAD

**Issue by ghisbo** [DannyBen/docker-snapcrawl#10]
Hello, 
i use the following

```
docker run --rm -it --volume "d:\snaps:\app" dannyben/snapcrawl example.com log_level=0 depth=1 width=1024 snaps_dir=snaps
```

but i do not get any result in d:\snaps.
what am i doing wrong

thanks in advance

**Comment by DannyBen** [comment]
The `snaps_dir` affects where snapshots are stored **in the container**, not on your host machine. Remove it. Snapshots will then be stored inside the `/app` folder in the container, and this is the folder you need to mount.

Second, this may or may not be an issue (I am not using docker on Windows so I cannot be sure), but you may need to change the slashes in the volume mount.

See if any of these commands work (copy them exactly, do not alter):

```
docker run --rm -it --volume d:\snaps:\app dannyben/snapcrawl example.com depth=1

docker run --rm -it --volume d:\snaps:/app dannyben/snapcrawl example.com depth=1

docker run --rm -it --volume d:/snaps:/app dannyben/snapcrawl example.com depth=1
```

**Comment by ghisbo** [comment]
Thank you
the working commands 
are 2 and 3 
docker run --rm -it --volume d:\snaps:/app dannyben/snapcrawl example.com depth=1

docker run --rm -it --volume d:/snaps:/app dannyben/snapcrawl example.com depth=1

files end uo in the folder d:\snaps\snaps

thanks

**Comment by DannyBen** [comment]
Cool. I will close this issue then.
