### ISSUE TITLE
docker: invalid reference format

### ISSUE THREAD

**Issue by persac** [DannyBen/docker-snapcrawl#9]
After running
`alias snapcrawl='docker run --rm -it --volume $PWD:/app dannyben/snapcrawl'`
and
`snapcrawl --version`
docker returned
`docker: invalid reference format: repository name must be lowercase.`

This can be fixed like so:
`alias snapcrawl='docker run --rm -it --volume "$PWD:/app" dannyben/snapcrawl'`

**Comment by DannyBen** [comment]
Did you have spaces in your current directory when that happened?

**Comment by DannyBen** [comment]
Anyways - thanks, I updated the README.

**Comment by persac** [comment]
> Did you have spaces in your current directory when that happened?

Not in the current directory name, but in the full path, yes. That may have caused the issue indeed!
